#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Thu Apr 30 11:18:19 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, _("Exit"), "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, _("File"))
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(2, 0)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("LED On/Off"))
        self.checkbox_1 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_1"))
        self.label_2 = wx.StaticText(self, wx.ID_ANY, _("LED 1"))
        self.checkbox_2 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_2"))
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _("LED 2"))
        self.checkbox_3 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_3"))
        self.label_4 = wx.StaticText(self, wx.ID_ANY, _("LED 3"))
        self.checkbox_4 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_4"))
        self.label_5 = wx.StaticText(self, wx.ID_ANY, _("LED 4"))
        self.checkbox_5 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_5"))
        self.label_6 = wx.StaticText(self, wx.ID_ANY, _("LED 5"))
        self.checkbox_6 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_6"))
        self.label_7 = wx.StaticText(self, wx.ID_ANY, _("LED 6"))
        self.checkbox_7 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_7"))
        self.label_8 = wx.StaticText(self, wx.ID_ANY, _("LED 7"))
        self.checkbox_8 = wx.CheckBox(self, wx.ID_ANY, _("checkbox_8"))
        self.label_9 = wx.StaticText(self, wx.ID_ANY, _("LED 8"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("default"))
        self.SetSize((700, 350))
        self.frame_1_statusbar.SetStatusWidths([-1, -1])
        # statusbar fields
        frame_1_statusbar_fields = [_("Created with wxGlade!"), _("Click the radio button to light the LED")]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(9, 2, 10, 10)
        grid_sizer_1.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_9, 0, wx.ADJUST_MINSIZE, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.SetSizeHints(self)
        grid_sizer_1.AddGrowableCol(1)
        self.Layout()
        # end wxGlade

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()